import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { runProcess } from "../src/runs/process.js";
import { createCompanionServer } from "../src/api/server.js";

test("本地 API 暴露健康检查、协议版本和任务创建", async (t) => {
  const temp = await mkdtemp(path.join(os.tmpdir(), "aca-server-"));
  t.after(() => rm(temp, { recursive: true, force: true }));
  const repo = path.join(temp, "repo");
  await runProcess("git", ["init", "-b", "main", repo]);
  await runProcess("git", ["-C", repo, "config", "user.name", "Server Test"]);
  await runProcess("git", ["-C", repo, "config", "user.email", "server@example.test"]);
  await writeFile(path.join(repo, "README.md"), "test\n");
  await runProcess("git", ["-C", repo, "add", "."]);
  await runProcess("git", ["-C", repo, "commit", "-m", "initial"]);
  const config = { host: "127.0.0.1", port: 0, deepseekApiKey: "", deepseekModel: "deepseek-v4-flash", deepseekBaseUrl: "https://api.deepseek.com", harnessPackage: "@deepseek-ai/dsh", maxRequestBytes: 4 * 1024 * 1024 };
  const harness = { async run() { return { code: 0, stdout: "ok", stderr: "" }; } };
  const { server } = await createCompanionServer({ config, runtimeRoot: path.join(temp, "runtime"), harness });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise((resolve) => server.close(resolve)));
  const port = server.address().port;
  const health = await fetch(`http://127.0.0.1:${port}/api/health`).then((response) => response.json());
  assert.equal(health.ok, true);
  assert.equal(health.protocolVersion, "1.0");
  const consoleResponse = await fetch(`http://127.0.0.1:${port}/`);
  assert.equal(consoleResponse.status, 200);
  assert.match(await consoleResponse.text(), /DeepSeek Harness · 接口现场助手/);
  const blockedOrigin = await fetch(`http://127.0.0.1:${port}/api/health`, { headers: { Origin: "https://untrusted.example" } });
  assert.equal(blockedOrigin.status, 403);
  const extensionOrigin = await fetch(`http://127.0.0.1:${port}/api/health`, { headers: { Origin: "chrome-extension://test-extension-id" } });
  assert.equal(extensionOrigin.status, 200);
  assert.equal(extensionOrigin.headers.get("access-control-allow-origin"), "chrome-extension://test-extension-id");
  const response = await fetch(`http://127.0.0.1:${port}/api/tasks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ protocolVersion: "1.0", source: { extensionVersion: "0.8.1" }, task: { name: "API task" }, target: { projectPath: repo, targetBranch: "main" }, evidence: {} }) });
  assert.equal(response.status, 201);
  const created = await response.json();
  assert.equal(created.task.status, "received");
  const oversized = await fetch(`http://127.0.0.1:${port}/api/tasks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: `{"payload":"${"x".repeat(4 * 1024 * 1024 + 32)}"}` });
  assert.equal(oversized.status, 413);
});
